name: 'Install'
description: 'Sets up Node.js and runs install'
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.1.0
      with:
        version: '10.16.1'
    - uses: actions/setup-node@v5
      with:
        node-version: 24
        cache: 'pnpm'
    - shell: bash
      run: pnpm install
    - shell: bash
      run: pnpm build
